---
volumes:
  data:
  transcode:

services:
  plex:
    container_name: plex
    image: plexinc/pms-docker
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Vienna
      - PLEX_CLAIM=${CLAIM_CODE}
      - ADVERTISE_IP=http://192.168.10.21:32400/
    ports:
      - 32400:32400/tcp
      - 8324:8324/tcp
      - 32469:32469/tcp
      - 1900:1900/udp
      - 32410:32410/udp
      - 32412:32412/udp
      - 32413:32413/udp
      - 32414:32414/udp
    volumes:
      - data:/config
      - transcode:/transcode
      - /mnt/hdd/media:/data