networks:
  guac:
    driver: bridge

volumes:
  db:

services:
  guacd:
    container_name: guacd
    image: guacamole/guacd
    networks:
      - guac
    restart: always

  postgres:
    container_name: guacamole_db
    environment:
      PGDATA: /var/lib/postgresql/data/guacamole
      POSTGRES_DB: guacamole_db
      POSTGRES_PASSWORD: test123
      POSTGRES_USER: guacamole_user
    image: postgres:15.2-alpine
    networks:
      - guac
    restart: always
    volumes:
    - ./init:/docker-entrypoint-initdb.d:z
    - db:/var/lib/postgresql/data:Z

  guacamole:
    container_name: guacamole
    depends_on:
    - guacd
    - postgres
    environment:
      GUACD_HOSTNAME: guacd
      POSTGRES_DATABASE: guacamole_db
      POSTGRES_HOSTNAME: postgres
      POSTGRES_PASSWORD: test123
      POSTGRES_USER: guacamole_user
    image: guacamole/guacamole
    networks:
      - guac
    ports:
    - 8080:8080/tcp # Guacamole is on :8080/guacamole, not /.
