volumes:
  data:
  
services:
  actual_server:
    container_name: actual
    image: docker.io/actualbudget/actual-server:latest
    ports:
      - '5006:5006'
    volumes:
      - data:/data
    restart: unless-stopped